services:
  # --- Frontend (Static Site) ---
  - type: static
    name: probax-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://probax-backend.onrender.com  # <-- metti qui l'URL del backend su Render (dopo il primo deploy)

  # --- Backend (FastAPI) ---
  - type: web
    name: probax-backend
    rootDir: backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: UVICORN_WORKERS
        value: "1"
